CREATE DATABASE CONTROL_ESTUDIANTES;
GO
USE CONTROL_ESTUDIANTES;
GO
--Creacion de tablas
CREATE TABLE ESTUDIANTES(
	ID INT PRIMARY KEY,
	NOMBRE_COMPLETO VARCHAR(255),
	CARNET VARCHAR(8),
	FECHA_NACIMIENTO DATE
);

CREATE TABLE MATERIAS(
	ID INT PRIMARY KEY,
	NOMBRE VARCHAR(255),
	CODIGO VARCHAR (255)
);

CREATE TABLE MATRICULAS(
	ID INT PRIMARY KEY IDENTITY(1,1),
	ID_ESTUDIANTE INT,
	ID_MATERIA INT,
	FECHA DATE,
	FOREIGN KEY (ID_ESTUDIANTE) REFERENCES ESTUDIANTES(ID),
	FOREIGN KEY (ID_MATERIA) REFERENCES MATERIAS(ID)
);

--Insercion de datos prueba
INSERT INTO ESTUDIANTES VALUES (1,'JHON JAMES BOYACA URIBE','856475', '1999-08-31')
INSERT INTO MATERIAS VALUES (1, 'MATEMATICAS BASICA', 'MB24')
INSERT INTO MATRICULAS VALUES (1,1,1,'2025-06-27')

INSERT INTO ESTUDIANTES VALUES (2,'JHON BOYACA','958741', '1999-08-31')
INSERT INTO MATERIAS VALUES (2, 'MATEMATICAS AVANZADA', 'MA24')
INSERT INTO MATERIAS VALUES (3, 'PROGRAMACION BASICA', 'PB25')


USE CONTROL_ESTUDIANTES
GO
--Creacion de vista Estudiante_Materia
CREATE VIEW VW_ESTUDIANTE_MATERIA AS
SELECT  
    e.NOMBRE_COMPLETO,
    e.CARNET,
    e.FECHA_NACIMIENTO,
    t.NOMBRE AS NOMBRE_MATERIA,
    t.CODIGO AS CODIGO_MATERIA,
    m.FECHA AS FECHA_MATRICULA,
    m.ID AS MATRICULA_ID
FROM MATRICULAS m
INNER JOIN MATERIAS t ON m.ID_MATERIA = t.ID
INNER JOIN ESTUDIANTES e ON m.ID_ESTUDIANTE = e.ID